rgeo/activerecord-postgis-adapter

lib/active_record/connection_adapters/postgis_adapter/oid/spatial.rb

Renaming the method solves the issue of the method being called by ActiveRecord's LogSubscriber, which expects `OID::Spatial` to inherit or overwrite the `binary?` method of ActiveRecord's `Type::Value`.
If ActiveRecord called the method before this change a NoMethodError was thrown, since the `binary?` method was private.
This change renames the method since it's for internal use only.
---
Please see #164 for more details.
What do you think? Is the name okay? Or did I misunderstand the part about `binary?(string)` being used for internal use only?

Renames OID::Spatial#binary to #binary_string? -- Fixes #164

---

lib/active_record/connection_adapters/postgis_adapter/spatial_column.rb
lib/active_record/connection_adapters/postgis_adapter/spatial_table_definition.rb
test/ddl_test.rb

Fixes #161 and #167
Rather than the approach suggested in #161, I've made a small change that allows the dumped schema to be loaded.  ~~Not familiar enough with the codebase to write a proper test for this; can someone help out?~~ EDIT: I've added tests for both #161 and #167
Example schema.rb:
```ruby
create_table "poo", id: false, force: :cascade do |t|
t.geography "blah", limit: {:srid=>4326, :type=>"point", :geographic=>true}
end
```
`rake db:test:prepare` previously blew up on this schema, but works correctly now.

Allow dumped schema to be reloaded

---

lib/active_record/connection_adapters/postgis_adapter/oid/spatial.rb

Add optional coordinates (z,m) for spherical_factory when Spatial value initializing.

Add optional coordinates (z,m) for spherical_factory

---

.travis.yml

We are no longer using sudo. This will speed up Travis builds.

Upgrade to new Travis container builds

---

.travis.yml
test/ddl_test.rb
test/nested_class_test.rb

Hi! This is an attempt to get the tests passing for JRuby. The main issue is 3d007649bbfa99d6cff4faeeea05e8aa8567d7af, since JRuby and MRI behave differently here and I don't know what's the expected behavior and whether this should be considered public API at all. 
* JRuby's behavior is actually tested: https://github.com/jruby/activerecord-jdbc-adapter/blob/v1.3.19/test/db/postgresql/simple_test.rb#L173-L180
* I haven't found any tests or documentation for the opposite behavior in `activerecord` but I think it's intentional. I think it happens here: https://github.com/rails/rails/blob/7f18ea14c893cb5c9f04d4fda9661126758332b5/activerecord/lib/active_record/connection_adapters/postgresql/quoting.rb#L59-L68
Opinions?
EDIT: Just linking to the original issue: #198

Jruby support

---

lib/active_record/connection_adapters/postgis/setup.rb
test/setup_test.rb

Rails has no support for views natively, but several gems ([Scenic]
included), do add support for them. Using them with PostGIS can cause
the PostGIS views themselves to be dumped.
The PostGIS adapter already ignores its own tables. This change adds the
view names that I'm aware of to the list.
See: https://github.com/thoughtbot/scenic/issues/134
[Scenic]: https://github.com/thoughtbot/scenic

Ignore PostGIS views when schema dumping

---

README.md

This is an option that appears to have been supported since 2.x, but is missing from the documentation.
Because my database uses postgis within the `postgis` schema instead of `public`, this configuration option was necessary when upgrading to 2.x.

Add missing configuration option to README

---

lib/active_record/connection_adapters/postgis/schema_statements.rb
lib/active_record/connection_adapters/postgis/spatial_column.rb

SpatialColumn inherits from PostgreSQLColumn (which inherits from [`Column`](https://github.com/rails/rails/blob/e8c21ff645eefb889acd7799bd12c9757cd8fd8c/activerecord/lib/active_record/connection_adapters/column.rb)) and it's call to super should match it's own initialize signature.
This change is related to rgeo/activerecord-postgis-adapter#175 because under the right circumstances, `default_function` is passed to super with a nil value setting the wrong default_function.
@teeparham I'd like to hear your thoughts on how to test this out...

Call to super does not match initialize parameters

---

lib/active_record/connection_adapters/postgis/schema_statements.rb
test/tasks_test.rb

This picks up on @miwelc's work from https://github.com/rgeo/activerecord-postgis-adapter/pull/192. It updates it to merge cleanly on master and adds tests.
This overall issue is a bit fuzzier now than it used to be, since activerecord-jdbc-adapter 1.3.18+ no longer exhibits this issue by default (the jdbc adapter now uses the same default behavior as the normal postgresql adapter). However, it's still possible this bug can crop up if you're using an older version of activerecord-jdbc-adapter (before 1.3.18) or if you've tweaked the `ActiveRecord::ConnectionAdapters::PostgreSQLJdbcConnection.raw_boolean` setting. So it would still be nice to see this fixed. For a bit more detail on the recent activerecord-jdbc-adapter changes, see: …

Fix schema dump null issues in JRuby

---

lib/active_record/connection_adapters/postgis_adapter.rb
lib/activerecord-postgis-adapter.rb

Issue described in #236
PostGISDatabaseTasks is not multithread-prof. It should be required on needed.

Autoload PostGISDatabaseTasks to avoid memory leaks in multithread

---

lib/active_record/connection_adapters/postgis/create_connection.rb

pg 0.21 emits warnings
```
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.
```

Use PG::Connection instead of PGconn

---

lib/active_record/connection_adapters/postgis/oid/spatial.rb

This fixes:
1. ruby warning: `warning: character class has duplicated range: /[geography,geometry]\((.*)\)$/`
2. wrongly matches of any type for which the name ends with any of the characters: g, e, o, r, a, p, h, y, m, t

fix regex for parsing spacial column types

---

.travis.yml
activerecord-postgis-adapter.gemspec

* Requires rgeo 1.0
If you are using proj.4, you must now require the rgeo-proj4 gem:
```ruby
gem "rgeo-proj4"
```

Require rgeo-activerecord 6.0

---

lib/active_record/connection_adapters/postgis/schema_statements.rb
lib/active_record/connection_adapters/postgis/spatial_column.rb
test/ddl_test.rb

Motivation:
I want to print column comments on `db/schema.rb` files.
It is default feature of rails5 since rails/rails#22911

Enable column comment

---

Appraisals
gemfiles/ar52.gemfile

Hi @teeparham, it seems that the `pg` gem has released a 1.0 but this library still ties the updates to `~>0.17`.
Do you think the Gemfile restriction can be updated to support 1.0?
Thank you!

Compatibility with pg-1.0.0

---

.gitignore
CONTRIBUTING.md
Gemfile
gemfiles/ar51.gemfile
gemfiles/ar52.gemfile
test/basic_test.rb
test/database.yml
test/ddl_test.rb
test/nested_class_test.rb
test/setup_test.rb
test/spatial_queries_test.rb
test/tasks_test.rb
test/test_helper.rb

With this commit, the tests pass against either PG 9.6 or 10.
Travis is still running PG 9.6. The update to travis will
need to be done in a separate commit, since Travis support for
PG 10 is still questionable.
* Fix task tests for PG 10
* Test with pg gem version 1.x
* Use ENV to configure the test database connection.
Use the same defaults, but allow overriding with any of these:
PGHOST
PGDATABASE
PGPORT
PGUSER
PGPASSWORD

Fix tests for Postgres 10

---

CONTRIBUTING.md
lib/active_record/connection_adapters/postgis/schema_statements.rb
test/schema_statements_test.rb

Since the Rails 6 upgrade, we started seeing some random PostGIS
serialization/deserialization issues, debugging the issues shows that the
ActiveRecord connection `type_map` isn't initialized properly.
It does not contain the PostGIS OID type mappings after `initialize_type_map` has ended.
Usually, Rails would add missing OID mappings when encountered, however,
there are code paths that go around this (See [`lookup_cast_type_from_column`](https://github.com/rails/rails/blob/15748f6a052d4df68b6acf66456c181b42d9fe25/activerecord/lib/active_record/connection_adapters/postgresql/quoting.rb#L78)).
This is most likely a bug in Rails internals.
This patch fixes the [`initialize_type_map`](https://github.com/rgeo/activerecord-postgis-adapter/blob/cc0e3f53520feed0b43800d8ee86561ee03de413/lib/active …

Fix SchemaStatements#initialize_type_map

---

.travis.yml
lib/active_record/connection_adapters/postgis/column_methods.rb
lib/active_record/connection_adapters/postgis/schema_statements.rb
lib/active_record/connection_adapters/postgis/spatial_table_definition.rb

Ruby 2.7.0 was released December 25, 2019, and has some noisy [deprecation messages about keyword arguments](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/).
`activerecord-postgis-adapter` calls multiple methods from ActiveRecord that have kwargs as the last argument and produce warnings in stdout.
So, what's done here:
* Add Ruby 2.7 to Travis matrix
* Get rid of kwargs deprecation messages from postgis-adapter
We still need to wait for Rails team to release a new version of ActiveRecord which will also has fixes for it's own deprecation messages.

Add support for Ruby 2.7

---

README.md

Apologies, my OCD.
You can check the code here: https://codeclimate.com/github/rgeo/activerecord-postgis-adapter/badges#maintainability-markdown
https://github.com/tagliala/activerecord-postgis-adapter/tree/chore/use-svg-badge#postgis-activerecord-adapter

Use SVG version of Code Climate badge

---

History.md
lib/active_record/connection_adapters/postgis/databases.rake
lib/active_record/connection_adapters/postgis/version.rb

Fixes #328.
Missed this in testing for ActiveRecord 6.1 upgrade because it is in a Rake task and requires rails. The solution is passing the new `DatabaseConfig` object to the task instead of a plain hash.

Update db:gis:setup Task for ActiveRecord 6.1

---

lib/active_record/connection_adapters/postgis/databases.rake

The previous code with the string 'database' does no longer work in current Rails versions.
Configuration hash uses symbols since Rails 6.1. See 
https://github.com/rails/rails/commit/ce9b197cc902ce8b72b7b3b5a3ec7e507fdba858

Access configuration_hash using symbols

---

lib/active_record/connection_adapters/postgis/database_statements.rb
lib/active_record/connection_adapters/postgis_adapter.rb

Fix for #342 and #337.
Instead of prepending the `DatabaseStatements` from #338, this includes it into the PostGIS adapter. Should fix issues where it would not be properly included in testing environments.

Include PostGIS::DatabaseStatements in Adapter

---

lib/active_record/connection_adapters/postgis_adapter.rb
test/basic_test.rb
test/ddl_test.rb

Fixes #344.
Overrides the `quote_default_expression` method to properly handle spatial data.

Fix Default Values

---

lib/active_record/connection_adapters/postgis/spatial_table_definition.rb
test/ddl_test.rb

This fixes when using generated geometry column from schema.rb
ref #369
`type_to_sql` had been removed in https://github.com/rgeo/activerecord-postgis-adapter/pull/360/files#diff-eeeb5e84f6023e4b440660467863dbed44712213c7c65db4e6fe401a3c219b1cL37-L57 as the adapter knows how to handle limits as strings. But in this situation, it is as a hash

overload type_to_sql

---

lib/active_record/connection_adapters/postgis/schema_statements.rb
test/cases/ddl_test.rb

I switched from the official postgressql adaptor to this adaptor, and noticed that some virtual columns in my database started schema dumping incorrectly. In particular the `as` function would dump as nil 
```schema.rb
postgressql adaptor ->
t.virtual "birthdate_text", type: :text, as: "birthdate", stored: true
postgis adaptor ->
t.virtual "birthdate_text", type: :text, as: nil, stored: true
```
I did some investigation and it looks like your adaptor is missing a recent change @fatkodima made that fixes this issue. here
https://github.com/rails/rails/commit/7fa2720b09e044c79764329e3f0a23aab13ffb89
I copied his change and added a spec to cover the scenario. I tried to do my best to adhere to the style and format of the existing tests, but can make additional changes if needed. 
Thank you …

Virtual column schema dump - default_function - Bring in recent postgressql adaptor change

---

lib/active_record/connection_adapters/postgis/schema_statements.rb
lib/active_record/connection_adapters/postgis/spatial_column.rb

https://github.com/rails/rails/pull/49504 introduced a new `identity` argument on the `ActiveRecord::ConnectionAdapters::PostgreSQL::Column#initialize` method which is causing the dumping of virtual columns to be treated as identity columns. 
This PR updates the methods to match the new ones on the Postgres adapter.

Pass new identity attribute to preserve argument order

---

lib/active_record/connection_adapters/postgis_adapter.rb

This is needed to support `db console` and probably others in rails 7.1 after https://github.com/rails/rails/pull/46093/ was merged.
This fixes (for me) #387

add the ConnectionHandling module

---

README.md

The "Creating a Spatial Rails App" previously said "The adapter will add the PostGIS extension to your database.", which isn't true since this commit: https://github.com/rgeo/activerecord-postgis-adapter/commit/418c02706291a595ac4e748d18f5c64459444ad2
I updated the readme instructions to add the migration to create the extension in the "Creating a Spatial Rails App" section. It was then almost identical to the "Upgrading an Existing Database" section, so I merged the two into a new section called "Setup". 
I also went for the newer style `default: &default` style for the `config/database.yml` part. 
Fixes issue https://github.com/rgeo/activerecord-postgis-adapter/issues/389
Thanks @BuonOmo for the pointers

Clarify extension creation instructions in README

---

test/cases/basic_test.rb
test/cases/ddl_test.rb
test/cases/schema_statements_test.rb

Fix tests setup and reset of #405:
Load current default spatial factory value as is instead of making rgeo produce one. Default factory produced by rgeo is not memoized by rgeo, but the set one is.
Resetting the default to a produced was fixing it to one fixed value.
Revert to use ActiveSupport::TestCase instead of ActiveRecord::TestCase on dd_test, it was causing the tests to attempt loading an misconfigured db connection.

Fix tests of #405 "Bump to 7.2.0"

---

test/cases/basic_test.rb

Fix teardown and clean related code

Fix test teardown

---

lib/active_record/connection_adapters/postgis/quoting.rb
lib/active_record/connection_adapters/postgis_adapter.rb
test/cases/spatial_queries_test.rb

From https://github.com/rgeo/activerecord-postgis-adapter/issues/402#issuecomment-2371701919 in https://github.com/rgeo/activerecord-postgis-adapter/issues/402
Includes a test that specifically verifies this query syntax

apply quoting patch

---

lib/active_record/connection_adapters/postgis_adapter.rb
lib/activerecord-postgis-adapter.rb

Fixes #415.
This issue seems to only happen if a connection isn't created during startup. Not sure why other representative apps don't have this problem - there might be something in an initializer that creates the connection before trying to run the rake task. But from a pure perspective, the postgis adapter file may not load by the time the db:create tasks runs.
This PR moves the registration to the topmost file, which seems to solve this problem.

Fix loading issue with rake db:create on Rails 7.2

---

.github/workflows/tests.yml
.gitignore
activerecord-postgis-adapter.gemspec
test/database.yml
test/excludes/ActiveRecord/ConnectionAdapters/RegistrationIsolatedTest.rb
test/excludes/CounterCacheTest.rb
test/excludes/SchemaDumperTest.rb

This PR is #419, plus:
* Remove ruby 3.1 from the test matrix, since rails 8 requires ruby 3.2
* Add ruby 3.4 to the test matrix
* Update the .gitignore file

Add Rails 8 support
